onaio/tasking

Pipfile, Pipfile.lock, README.md, docs/design.md, docs/installation.md, setup.py
- Improve documentation
- Add install_requires to setup.py
=> Setup.py fix

tasking/models/tasks.py
=> Task Status Field Changes: STATUS_CHOICES

tests/serializers/test_tasks.py
=> Update TaskSerializer Tests

tasking/viewsets/__init__.py, tasking/viewsets/locations.py, tests/serializers/test_location.py, tests/viewsets/test_locations.py
=> Add Location Viewsets

tasking/urls.py, tasking/viewsets/__init__.py, tasking/viewsets/projects.py, tests/viewsets/test_projects.py, tests/viewsets/test_tasks.py
- Add ProjectViewSet
- Add ProjectViewSet tests
- Rename task viewset tests to test_tasks.py
Fix: #32
=> Add projects viewset

tasking/viewsets/submissions.py, tests/viewsets/test_submissions.py
=> Add Submission Filtering, Searching, & Ordering

tasking/viewsets/tasks.py, tests/settings.py, tests/viewsets/test_tasks.py
=> Add task filter

tasking/viewsets/projects.py, tests/viewsets/test_projects.py
=> Add sorting, searching and ordering for Projects ViewSet

tasking/serializers/segment_rule.py, tests/serializers/test_segment_rules.py, tests/viewsets/test_tasks.py
=> Add target_field validation on SegmentRule serializer

tox.ini
Current coverage report:
```sh
Name                                  Stmts   Miss  Cover
---------------------------------------------------------
tasking/__init__.py                       4      0   100%
tasking/common_tags.py                   10      0   100%
tasking/exceptions.py                     5      0   100%
tasking/models/__init__.py                7      0   100%
tasking/models/base.py                   23      0   100%
tasking/models/locations.py              28      0   100%
tasking/models/projects.py               17      0   100%
tasking/models/segment_rules.py          23      0   100%
tasking/models/submissions.py            25      0   100%
tasking/models/tasks.py                  34      0   100%
tasking/serializers/__init__.py           7      0   100% …
```
=> Increase test coverage

tasking/viewsets/locations.py, tests/viewsets/test_locations.py
=> Add sorting, filtering and ordering for Locations

Pipfile, Pipfile.lock, setup.py, tasking/serializers/location.py
backports.tempfile provides support for TemporaryDirectory in python 2.7
=> Add backports.tempfile

tasking/serializers/task.py, tasking/utils.py, tests/serializers/test_submissions.py, tests/serializers/test_tasks.py, tests/settings.py, tests/test_utils.py, tests/viewsets/test_locations.py, tests/viewsets/test_projects.py, tests/viewsets/test_submissions.py, tests/viewsets/test_tasks.py
=> Sync Task model fields: start, end and timing_rule

docs/api/projects.md
=> Add Project API Documentation

docs/api/contenttype.md, tasking/urls.py
=> Add Documentation for ContentType API Endpoint

docs/api/locations.md
=> Add Locations API Endpoint Documentation

docs/api/submissions.md
=> Add Submissions API Endpoint Documentation

docs/api/segmentrules.md
=> Add Documentation for SegmentRules API Endpoint

docs/api/task.md
=> Add Task API Endpoint Documentation

docs/api/projects.md
=> Update Projects API Documentation

tests/viewsets/test_locations.py, tests/viewsets/test_projects.py, tests/viewsets/test_segment_rules.py, tests/viewsets/test_submissions.py, tests/viewsets/test_tasks.py
Fixes some inconsistencies i found in the code.
=> Fix Some Inconsistencies in Code

tasking/models/managers.py, tasking/models/tasks.py, tasking/serializers/task.py, tasking/viewsets/tasks.py, tests/serializers/test_tasks.py, tests/viewsets/test_tasks.py
=> Add Submission Count to Tasks

docs/api/task.md
=> Add information to Task API Documentation

docs/models/managers/task_manager.md
=> Add TaskManager Documentation

tasking/__init__.py, tasking/models/locations.py, tasking/models/occurrences.py, tasking/models/projects.py, tasking/models/segment_rules.py, tasking/models/submissions.py, tasking/models/tasks.py
=> Add app labels

tasking/utils.py
Pass the OccurrenceModelClass as an argument to generate_task_occurrences
Closes #113
=> Add arg OccurrenceModelClass to generate_task_occurrences

Pipfile.lock, setup.py, tasking/__init__.py, tasking/common_tags.py, tasking/filters.py, tasking/models/base.py, tasking/models/locations.py, tasking/models/locationtypes.py, tasking/models/occurrences.py, tasking/models/projects.py, tasking/models/segment_rules.py, tasking/models/submissions.py, tasking/models/tasks.py, tasking/serializers/contenttype.py, tasking/serializers/location.py, tasking/serializers/locationtype.py, tasking/serializers/occurrence.py, tasking/serializers/project.py, tasking/serializers/segment_rule.py, tasking/serializers/submissions.py, tasking/serializers/task.py
=> Handle float values of geopoint & others

Pipfile, Pipfile.lock, setup.py, tasking/__init__.py, tasking/serializers/location.py
- Fix dependencies
- Use backwards compatible version of builtins
=> Version 0.2.0 

.travis.yml, Pipfile, Pipfile.lock, setup.py, tasking/__init__.py, tasking/common_tags.py, tasking/exceptions.py, tasking/serializers/location.py, tests/serializers/test_contenttype.py, tests/serializers/test_location.py, tox.ini
=> Fix shapefile issues

.github/FEATURE_REQUEST_TEMPLATE.md, .github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.md
=> Add contributor guidelines and templates for issues, pull requests and feature requests

.pre-commit-config.yaml, .travis.yml, setup.cfg, setup.py, tasking/apps.py, tasking/models/base.py, tasking/models/locations.py, tasking/models/submissions.py, tasking/serializers/location.py, tasking/serializers/project.py, tasking/serializers/submissions.py, tasking/viewsets/__init__.py, tasking/viewsets/contenttype.py, tasking/viewsets/occurrences.py, tasking/viewsets/submissions.py, tests/serializers/test_tasks.py, tests/test_exceptions.py, tests/test_utils.py, tests/viewsets/test_tasks.py, tox.ini
- Ensure isort runs on pre-commit and that our CI checks to make sure
our codebase is checked by isort on push
- Format all files using isort
- Ran `pre-commit run --all-files`
- Tested with tox
- Tested on travis
- All new files from this point on wards will be formatted by isort.
Closes #165
=> Configure isort to work on travis and pre-commit
